name: Documentation Build Test
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [11, 12]
    name: Run Doc Tests -- Python 3.${{ matrix.pyver }}
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: sudo apt-get install -y pandoc
      - uses: actions/setup-python@v4
        with:
          python-version: 3.${{ matrix.pyver }}
      - name: Install tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3${{ matrix.pyver }}-docs
