name: Unit Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [11, 12]
    name: Run Unit Tests -- Python 3.${{ matrix.pyver }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.${{ matrix.pyver }}
      - name: Install tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3${{ matrix.pyver }}-unit
      - name: Generate coverage report
        if: matrix.pyver == 11
        run: tox -e coverage
      - name: Upload coverage report
        if: matrix.pyver == 11
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          flags: unit,gha,python-3.${{ matrix.pyver }}
